grafana:
  enabled: true
  adminPassword: test
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: self-signed-cluster-issuer
    hosts: []
    path: /
    tls:
      - secretName: dash-test-tls
        hosts:
          - dash.192.168.3.125.nip.io
    persistence:
    enabled: true
    type: sts
    storageClassName: "local-path"
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection
