 authentik:
  log_level: debug
  secret_key: ""

  error_reporting:
    enabled: false

  postgresql:
    password: ""

server:
  ingress:
    ingressClassName: traefik
    enabled: true
    hosts:
      - auth.192.168.3.125.nip.io
    annotations:
      cert-manager.io/cluster-issuer: self-signed-cluster-issuer
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authentik-server
            port:
              number: 80
    tls:
      - secretName: authentik-tls
        hosts:
          - auth.192.168.3.125.nip.io

  # authentik server configuration
  name: server
  replicas: 1

worker:
  name: worker
  replicas: 1

postgresql:
  enabled: true
  auth:
    password: ""  # Keep this blank because the password is in the secret

redis:
  enabled: true
  replicas: 1

global:
  affinity:
    nodeAffinity:
      type: hard
      matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - pubuntu1
    podAntiAffinity: soft
