authentik:
  log_level: debug
  #secret_key: ADD THIS
  #postgresql:
    #password: ADD THIS

server:
  ingress:
    ingressClassName: traefik
    enabled: true
    hosts:
      - auth.silverycat.de
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authentik-server
            port:
              number: 80
    tls:
      - secretName: auth-silverycat-de-tls
        hosts:
          - auth.silverycat.de
postgresql:
  enabled: true
  auth:
    #password: ADD THIS
redis:
  enabled: true
  replicas: 1

global:
  affinity:
    nodeAffinity:
      type: hard
      matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - pubuntu1
  podAntiAffinity: soft

## authentik server
server:
  name: server
  replicas: 1

## authentik worker
worker:
  name: worker
  replicas: 1
